# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171124_0708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Moment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='moment',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='moment',
        ),
    ]
